### ISSUE TITLE
Visual recognition service - error during listing custom classifiers

### ISSUE THREAD

**Issue by oszekely** [watson-developer-cloud/python-sdk#292] opened 2017-11-03 16:42 UTC
I am facing a problem with visual recognition service Python API. I had a discussion with Matthew Hill (Watson Visual Recognition service developer) and sometimes null value appears in custom classifiers list. It raises an error in Python call 
```python
VisualRecognitionV3('2016-05-20', api_key=key).list_classifiers(verbose=True)
```

**Comment by germanattanasio** [comment] 2017-11-03 20:07
@oszekely can you provide the code snippet (without apikey) that you are trying to use.

**Comment by oszekely** [comment] 2017-11-03 21:00
I can not send you error message now, because Matt removed the problematic classifier. Error comes from WDC SDK, not mine code. Problem is in list_classifiers() method of VisualRecognitionV3 instance. list_classifiers(verbose=True) throws error, list_classifiers(verbose=False) not. I suppose that problem is that in verbose=True JSON parser tries parse the null item, but it does not work. Thrown error was something in common with JSON parser, that it is unable to parse it, but I did not save the screen.

**Comment by ehdsouza** [comment] 2017-11-15 15:27
@oszekely, could you try if the problem exists with the new version(1.0.0) released?

**Comment by ammardodin** [comment] 2017-11-25 00:08
@ehdsouza `verbose` is no longer an option in the `list_classifiers` method in the latest release. I, however, tried manually using it since the service still supports it, and I failed to reproduce the issue. The `json` module can handle any `None` values in the returned dictionary from the service, and when calling `json.dumps`, the `json` module converts those values to `null` in the output string. Unless I am missing something, or someone can reproduce this, this shouldn't be an issue anymore. I am closing this for now, but feel free to re-open if someone can reproduce this issue.

**Closed by ammardodin** 2017-11-25 00:08 UTC
Labels: bug

**Comment by oszekely** [comment] 2017-12-01 20:18
Thank you all, I have updated asset, if it occurs once more, I will let you know, but I hope that it will not. :)
