### ISSUE TITLE
Incorrect hypothesis

### ISSUE THREAD

**Issue by zSeriesGuy** [watson-developer-cloud/python-sdk#699] opened 2019-10-14 17:57 UTC
I think this is may be more an issue for the cloud service than this SDK. If so, can you please forward this issue?

In the first interim results, the word "over" comes back in the interim result as %HESITATION.
Subsequent interim results and the final result is correct.
I am using streaming with the websocket in python.

**Comment by germanattanasio** [comment] 2019-10-14 17:59
The service is returning `%HESITATION`. See https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-basic-response

**Comment by zSeriesGuy** [comment] 2019-10-14 18:04
Even when I don't hesitate in the sentence, it still inserts %HESITATION.
I said "the time is over". This is what on_hypothesis printed:
the 
the tie 
the time 
the time is 
the time is a 
the time is %HESITATION 
the time is over 
the time is over

**Comment by germanattanasio** [comment] 2019-10-14 18:54
I can't think of why that would happen but I don't think it's a problem with the SDK.

**Comment by zSeriesGuy** [comment] 2019-10-14 22:42
I agree that it is most likely not an issue with the SDK. But I don't know where to report this issue.
Can you confirm this behavior?
Can you report this to IBM Cloud services?

**Comment by ehdsouza** [comment] 2019-10-17 16:23
@zSeriesGuy you could open a ticket for the service here: https://cloud.ibm.com/unifiedsupport/supportcenter

**Comment by zSeriesGuy** [comment] 2019-10-17 20:46
@ehdsouza Thank you. I'll do that. It would be nice if I could get confirmation that it is not my system or my coding. Is this something you can verify? If you run a streaming test, can you try saying the word "over" and see if you get %HESITATION back without actually hesitating?

**Comment by germanattanasio** [comment] 2019-12-05 14:18
It's not your system @zSeriesGuy. I can confirm that because I know the service returns that as part of a response. 

I'm going to close this because there is no issue with the SDK and you have a link to open a ticket for the service to fix the issue

**Closed by germanattanasio** 2019-12-05 14:18 UTC
Labels: support
