### ISSUE TITLE
Python SDK does not work in 3.6

### ISSUE THREAD

**Issue by drarvindsathi** [watson-developer-cloud/python-sdk#291] opened 2017-11-02 18:30 UTC
The Python Discovery SDK for add_doc is not working in Python 3.6.  Please see sdk slack for details and connect with Tibor.

**Comment by mkistler** [comment] 2017-11-03 17:43
Please provide details on the environment and the specific request and data to recreate the problem.  Or create an issue in the internal Dev Experience repo and provide details there.

Without clear information on what the problem is and how to recreate it, we cannot make any progress to address it.

**Comment by mkistler** [comment] 2017-11-06 02:39
Issue resolved by the submitter.

**Closed by mkistler** 2017-11-06 02:39 UTC
Labels: invalid
