### ISSUE TITLE
Unicode and Language Translation

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/python-sdk#22] opened 2015-11-23 22:29 UTC
Not sure if this is an issue or not but when passing in unicode to the language detection needs to be encoded. ie. if data is unicode then it has to be encoded

txt = data.encode("utf-8", "replace")

and the encoded text passed into identify

language_translation.identify(txt)

whereas 
language_translation.identify(data)
throws a unicode error.

**Comment by chughts** [comment] 2015-11-23 22:31
of course this is on my Python 3 environment.

**Comment by jsstylos** [comment] 2015-12-05 20:19
Does the source file contain "# coding=utf-8" at the top? The example for
Language Translation shows a utf-8 string being passed (to translate(), but
it also works for identify()) without the data.encode("utf-8") in a way
that works for Python 2 and 3.

**Comment by chughts** [comment] 2015-12-08 10:21
Yes it does, almost religiously.

**Comment by jsstylos** [comment] 2015-12-08 11:34
Can you post a small example that fails?

**Comment by saraswat** [comment] 2017-03-17 15:41
Curious why this was closed without resolution? I tried 
```
result = language_translator.identify(article)
```
with `article` a Chinese string, and got a unicode error. I had to do this to get a response from the service:
```
result = language_translator.identify(article.encode("utf-8"))
```

The underlying problem is captured by this portion of the backtrace:
```
/Users/vj/anaconda/lib/python3.6/site-packages/watson_developer_cloud/language_translator_v2.py in identify(self, text)
     35         return self.request(method='POST', url='/v2/identify', data=text,
     36                             headers={'content-type': 'text/plain'},
---> 37                             accept_json=True)
     38 
     39     def get_identifiable_languages(self):
...
/Users/vj/anaconda/lib/python3.6/http/client.py in _encode(data, name)
    159             "%s (%.20r) is not valid Latin-1. Use %s.encode('utf-8') "
    160             "if you want to send it encoded in UTF-8." %
--> 161             (name.title(), data[err.start:err.end], name)) from None
    162 
    163 

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-14: Body ('张燕生：中国从制造到智造转型难') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

So I would recommend either (a) fixing the code so it does not use `text/plain`, or (b) adding comments to the code so that a developer can pick up that s/he needs to explicitly call `.encode("utf-8")`

**Comment by jsstylos** [comment] 2017-03-17 17:07
I can't tell if this is the same issue or another one. The original issue was closed because it wasn't reproducible in the mainstream Python deployments only the SK ones.

Is there a concrete example that breaks the standard Python build?

**Comment by saraswat** [comment] 2017-03-18 13:04
Yes, of course -- the above traceback is from such an example. See the string at the end of the error message. 

```UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-14: Body ('张燕生：中国从制造到智造转型难') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.```

**Comment by jsstylos** [comment] 2017-03-29 19:39
I was able to reproduce this issue on Python 3+, although it worked fine on Python 2.7. Unfortunately, I haven't been able to find a good solution that works on both Python 2 and Python 3.

`'你好'.encode('utf-8')` works on Python 3 but not on Python 2. The following is the only code I've been able to get to work on Python 2 and 3 at the same time, but it's fairly inelegant and I'm not sure it's the right solution for the SDK:

```# coding=utf-8
import json
from watson_developer_cloud import LanguageTranslatorV2

try:
    import sys  
    reload(sys)  
    sys.setdefaultencoding('utf-8')
except:
    pass

language_translator = LanguageTranslatorV2(
    username='YOUR SERVICE USERNAME',
    password='YOUR SERVICE PASSWORD')

test_string = '你好'.encode('utf-8')

print(json.dumps(language_translator.identify(test_string), indent=2))```

Does anyone have suggestions for best practices of supporting unicode strings in SDKs while maintaining Python 2 and 3 compatibility?

**Comment by jsstylos** [comment] 2017-03-29 20:17
After some more digging, it sounds like the right solution is probably to conditionally encode the data (and json?) parameters to request when the Python version >= 3.

**Comment by saraswat** [comment] 2017-03-29 20:27
What happens if you encode in Python 2.x? Isn't the encoding idempotent?

**Comment by jsstylos** [comment] 2017-03-29 20:39
@saraswat Trying to `.encode('utf-8')` on Python results in the error: ```Traceback (most recent call last):
  File "test.py", line 16, in <module>
    test_string = '你好'.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

Looking at other SDKs it seems like conditionally encoding it is best practice.

**Comment by jsstylos** [comment] 2017-03-30 13:28
Should hopefully be fixed in https://github.com/watson-developer-cloud/python-sdk/pull/183

**Closed** 2017-03-30 17:16 UTC
