### ISSUE TITLE
Intermittent problem when using http sync transcription API

### ISSUE THREAD

**Issue by johann-petrak** [watson-developer-cloud/python-sdk#815] opened 2022-02-18 13:41 UTC
Using Python package version 5.3.1 with Python 3.8.12

I running a number of transcriptions and did get the following exception for a few of them. Running the exactly same thing again worked. 
This should not happen, if there is a problem a known/predictable exception should get raised. 

```
Traceback (most recent call last):
  File "./python/audio2txt.py", line 144, in <module>
    resp = speech_to_text.recognize(
  File "/home/johann/anaconda3/envs/asr-ibm/lib/python3.8/site-packages/ibm_watson/speech_to_text_v1.py", line 566, in recognize
    response = self.send(request, **kwargs)
  File "/home/johann/anaconda3/envs/asr-ibm/lib/python3.8/site-packages/ibm_cloud_sdk_core/base_service.py", line 300, in send
    response = self.http_client.request(**request,
  File "/home/johann/anaconda3/envs/asr-ibm/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/johann/anaconda3/envs/asr-ibm/lib/python3.8/site-packages/requests/sessions.py", line 687, in send
    r.content
  File "/home/johann/anaconda3/envs/asr-ibm/lib/python3.8/site-packages/requests/models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/johann/anaconda3/envs/asr-ibm/lib/python3.8/site-packages/requests/models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by apaparazzi0329** [comment] 2024-02-22 21:59
Closing this issue due to its age and inability to reproduce. If this is still an issue, please try again with the latest version of the python-sdk and reopen this issue.

**Closed by apaparazzi0329** 2024-02-22 21:59 UTC
Labels: wontfix
