### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 643: character maps to <undefined>

### ISSUE THREAD

**Issue by poornima198m** [watson-developer-cloud/python-sdk#642] opened 2019-03-03 07:37 UTC
### This is my code:
```py
import re
import os
import codecs
import tarfile
import json as js

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
english_stopwords = stopwords.words('english')


def clean_math(string):
    
    while string.count('$') > 1:
        pos0 = string.find('$')
	#print (pos0)
        pos1 = string.find('$', pos0+1)
	#print(pos1)
        string = (string[:pos0] + string[:pos1]).strip()
    return string
        

def clean_str(string):
    """
    Input:
        string: One line in a latex file.
    Return：
        string cleaned.
    """
   
    # Remove mathematical formulas between $$
    string = clean_math(string)
    #print(string)

    # Remove "ref" 
    string = re.sub(r'~(.*)}', '', string)
    string = re.sub(r'\\cite(.*)}', '', string)
    string = re.sub(r'\\newcite(.*)}', '', string)
    string = re.sub(r'\\ref(.*)}', '', string)
    
    # Remove stopwords
    texts_tokenized = [word.lower() for word in word_tokenize(string)]
    texts_filtered_stopwords = [word for word in texts_tokenized if not word in english_stopwords]
    string = ' '.join(texts_filtered_stopwords)
    string = string.replace(',', '')
    string = string.replace('.', '')
    string = string.replace('?', '')
    string = string.replace('!', '')
    string = string.replace('/', '')
    string = string.replace('$', '')
    string = string.replace('~', '')
    string = string.replace('\\', '')
    string = string.replace('{', '')
    string = string.replace('}', '')
    string = string.replace('#', '')
    string = string.replace('&', '')
    string = string.replace('@', '')
    string = string.replace('%', '')
    string = string.replace('^', '')
    string = string.replace('*', '')
    string = string.replace('-', '')
    string = string.replace('=', '')
    string = string.replace('[', '')
    string = string.replace(']', '')
    string = string.replace('+', '')
    string = string.replace('(', '')
    string = string.replace(')', '')
    return string
    
    
def process_text_list(text_list):
    """
    Input:
        text_list: Content of a latex file and each element represents a line.
    Return:
        A list, which is the cleaned content of a latex file.
    """

    result = ''
    for line in text_list:
        line = line.strip()
        if line.startswith('%') or line.startswith('\\') or line == '':
            pass
        elif line[0].isdigit():
            pass
        else:
            result += clean_str(line)
    return result


# Extract Introduction, related work, etc.
def split(tex_list, start_char, end_char):
    lines = tex_list
    length = len(lines)
    start = None
    end = None
    i = 0
    while i < length and (end is None):
        if start is None:
            if lines[i].startswith(start_char):
                start = i + 1
        else:
            if lines[i].startswith(end_char):
                end = i
        i += 1
    if (start is not None) and (end is None):
        end = length
    return lines[start:end]


def extract(tex_list, segment=False):
    data = tex_list
    text = ' '.join(data)
    intro = ' '.join(split(tex_list, '\section{Intro', '\section{'))
    print('intro',intro)
    related = ' '.join(split(tex_list, '\section{Related', '\section{'))
    conclusion = ' '.join(split(tex_list, '\section{Conclu', '\section{'))
    methods = text.replace(intro, '').replace(related, '').replace(conclusion, '')
    if segment:
        pass
    else:
        return list(map(process_text_list, 
                    [intro.split('\n'), related.split('\n'), methods.split('\n'), conclusion.split('\n')]))



result = {}
file_names = os.listdir('AAPR_Dataset')
#print(file_names)
with open('a.txt','w')as f1:
    for file_name in file_names:
        f_name = os.path.join('AAPR_Dataset', file_name)
        with open(f_name) as f:
            data=f.read()
            tex_list = clean_str(data)
            print('tex_list',tex_list)
            var = process_text_list(tex_list)
            print('var',var)
            var2 = extract(tex_list, segment=False)
            f1.write(str(var2))
            f1.write(str(file_name))
            try:
                f_name = os.path.join('AAPR_Dataset', file_name)
	    #print(f_name)
                tex_list = make_single_tex(f_name)
	            #print (tex_list)
                result[file_name] = extract(tex_list)
            except:
                continue
            print (result)
	]([url](url))	
```

### My Input file is:

```json
{
   "1009.4013":{
      "abstract":"many firms days opting specialize rather generalize way maintaining competitiveness  consequently  rely solely  must cooperate combining advantages  obtain actual condition cooperation  multilayered network based two different types data investigated  first type transaction data japanese firms  network created data included 961363 firms 7808760 links  second type data jointpatent applications japan  jointpatent application network included 54197 nodes 154205 links  two networks merged one network  first anaysis based inputoutput tables three different tables compared  correlation coefficients tables revealed transactions strongly tied jointpatent applications total amount money  total amount money transactions relationships probably connected jointpatent applications different mechanisms  second analysis conducted based p model  choice  multiplicity  reciprocity  multireciprocity transitivity configurations evaluated  multiplicity reciprocity configurations significant analyzed industries  results multiplicity meant transactions jointpatent application links closely related  multireciprocity transitivity configurations significant analyzed industries  difficult find common characteristics industries  bayesian networks used third analysis  learned structure revealed transaction link two firms known  categories firms ' industries affect existence patent link ",
      "title":"an analysis of transaction and joint-patent application networks",
      "authors":"hiroyasu inoue",
      "category":"cs.SI,cs.CY",
      "tex_data":[
         "\\documentclass[11pt]{article}\r\n",
         "\r\n",
         "\\usepackage{fancybox}\r\n",
         "\\usepackage[dvips]{graphicx}\r\n",
         "\\usepackage{array}\r\n",
         "\\usepackage{lscape}\r\n",
         "\r\n",
         "%\u001b$B%U%m!<A43+@_Dj\u001b(B\r\n",
         "\\setcounter{topnumber}{10}\r\n",
         "\\setcounter{bottomnumber}{10}\r\n",
         "\\setcounter{totalnumber}{10}\r\n",
         "\\renewcommand{\\topfraction}{1}\r\n",
         "\\renewcommand{\\bottomfraction}{1}\r\n",
         "\\renewcommand{\\textfraction}{0}\r\n",
         "\\renewcommand{\\floatpagefraction}{1}\r\n",
         "\\renewcommand{\\floatsep}{3ex}\r\n",
         "\\renewcommand{\\textfloatsep}{3ex}\r\n",
         "\\renewcommand{\\intextsep}{3ex}\r\n",
         "\r\n",
         "\\voffset=0cm\r\n",
         "\\topmargin=-0.1cm\r\n",
         "\\headheight=0cm\r\n",
         "\\headsep=0cm\r\n",
         "% horizontal offsets: 2 cm from left\r\n",
         "\\hoffset=0cm\r\n",
         "\\marginparwidth=0cm\r\n",
         "\\marginparsep=0cm\r\n",
         "\\oddsidemargin=-0.4cm\r\n",
         "\\evensidemargin=\\oddsidemargin\r\n",
         "% A4 = 29.7 cm x 21.1 cm\r\n",
         "\\textwidth=17.0cm % 21.1 cm - 2*2 cm - alpha\r\n",
         "\\textheight=24.1cm % 29.7 cm - 2.5 cm - 3 cm - alpha\r\n",
         "\r\n",
         "%\\renewcommand{\\baselinestretch}{1.2}\r\n",
         "%\r\n",
         "\\begin{document}\r\n",
         "\r\n",
         "%\r\n",
         "%\\pagestyle{empty}\r\n",
         "%\r\n",
         "\r\n",
         "\\title{An Analysis of Transaction and Joint-patent Application Networks}\r\n",
         "\\author{Hiroyasu Inoue\\\\\r\n",
         "Osaka Sangyo University, Osaka 574-0013, Japan}\r\n",
         "\\date{}\r\n",
         "\r\n",
         "\\maketitle\r\n",
         "\r\n",
         "%\\vspace{2ex}\r\n",
         "\r\n",
         "\\begin{center}\r\n",
         "\\begin{minipage}[h]{14.0cm}\r\n",
         "\\begin{center}{\\bf Abstract}\\end{center}\r\n",
         "Many firms these days,\r\n",
         "forced by increasing international competition and\r\n",
         "an unstable economy, are opting to\r\n",
         "specialize rather than generalize as a way of maintaining their competitiveness.\r\n",
         "Consequently,\r\n",
         "they cannot rely solely on themselves, but must\r\n",
         "cooperate by combining their advantages.\r\n",
         "\r\n",
         "To obtain the actual condition for this cooperation,\r\n",
         "a multi-layered network\r\n",
         "based on\r\n",
         "two different types of data was investigated.\r\n",
         "The first type was transaction data from Japanese firms.\r\n",
         "The network created from the data included 961,363 firms and\r\n",
         "7,808,760 links.\r\n"
      ]
   }
}
```

**Comment by ehdsouza** [comment] 2019-03-04 21:32
@poornima198m could you give a more detailed explanation of what you are trying to do using the format specified for GH issue so that we can help you better?


**Overview**
_What is the issue? Be concise and clear._

**Expected behavior**
_What did you expect to happen?_

**Actual behavior**
_What actually happened?_

**How to reproduce**
_Help us to reproduce what you experienced. Include your code snippets (without credentials)_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
_Please provide the SDK version here._

**Additional information:**
- OS: _for example, iOS_
- Which version of `Python` are you using?

**Additional context**
_Add any other details about the problem._

**Comment by poornima198m** [comment] 2019-03-05 05:20
Input is latex file  and when i tried to open it  iam getting the error

**Comment by ehdsouza** [comment] 2019-03-13 13:03
@poornima198m, 
Did you try specifying the encoding when you open the file: `encoding="utf8"`?

**Comment by germanattanasio** [comment] 2019-03-30 21:14
None of the imports in your sample code comes from the SDK. This seems to be a generic python question. Try asking on stackoverflow.com

I'm closing this as invalid

**Closed by germanattanasio** 2019-03-30 21:14 UTC
Labels: support
