### ISSUE TITLE
Unable to classify zip files 

### ISSUE THREAD

**Issue by bcruga** [watson-developer-cloud/python-sdk#200] opened 2017-05-03 20:03 UTC
I've been trying to classify a .zip file using the example command:
-----------------------------------------------------------------
```python
from os.path import join, dirname
import json
from watson_developer_cloud import VisualRecognitionV3 as vr
    
instance = vr(vr.latest_version, api_key=["MY_API"])

with open(join(dirname(__file__), '..//file.zip'), 'rb') as image_file:
	results = instance.classify(images_file=image_file)
print(json.dumps(results))
```
-----------------------------------------------------------------
however, the only result I'm getting is this error
```
WatsonException: Error: No images were specified., Code: 400
```

Is there a specific way to zip files for Watson's VR?

**Comment by kognate** [comment] 2017-05-03 20:07
how many images are in the zip file file and how big are they?  If the zip file has more than 10 images and/or the images are larger than 2mb sometimes the error returned is not helpful. 

Also, what version of python are you using?

**Comment by bcruga** [comment] 2017-05-03 20:13
i've tried with 10 and 5 per zip, but all of them return the same. The file size is about 18kb, very small.

I'm using python 3.5

**Comment by jsstylos** [comment] 2017-05-04 14:48
Can you upload one of the zip files somewhere so we can reproduce?

**Comment by bcruga** [comment] 2017-05-05 18:38
[35.zip](https://github.com/watson-developer-cloud/python-sdk/files/979994/35.zip)

**Comment by jsstylos** [comment] 2017-05-05 19:00
This zip file works for me in Python 3.5.0 and 2.7.12. Are you sure that `'..//file.zip'` is picking up the right file? Do any other local files work for classification?

**Comment by bcruga** [comment] 2017-05-05 19:04
if i put a picture in which is in the same folder as the .zip, it works, but every zip i try, it fails. yeah the '..//file.zip' is the path to the zip file. I even tried putting both together in the same folder, and simply using with open ('35.zip', 'rb') ... but still gives the same error.

**Comment by jsstylos** [comment] 2017-05-05 19:21
One thing to try is to verify that the file is being loaded correctly by listing the contents of the zip file before trying to classify it:

```
with open(join(dirname(__file__), '../35.zip'), 'rb') as image_file:
    import zipfile

    zz = zipfile.ZipFile(image_file)
    zz.printdir()
    zz.close()
```

For me this prints out:

```
File Name                                             Modified             Size
35.png                                         2017-04-11 16:14:52         3268
36.png                                         2017-04-11 16:14:52         3133
37.png                                         2017-04-11 16:14:52         2828
38.png                                         2017-04-11 16:14:52         2594
39.png                                         2017-04-11 16:14:52         2661
40.png                                         2017-04-11 16:14:52         2878
```

**Comment by bcruga** [comment] 2017-05-05 20:00
File Name                                             Modified             Size
35.png                                         2017-04-11 16:14:52         3268
36.png                                         2017-04-11 16:14:52         3133
37.png                                         2017-04-11 16:14:52         2828
38.png                                         2017-04-11 16:14:52         2594
39.png                                         2017-04-11 16:14:52         2661
40.png                                         2017-04-11 16:14:52         2878

For me as well

**Comment by jsstylos** [comment] 2017-05-05 20:17
Very weird. Do you have the same issue when trying to use the Node SDK? Can you reproduce the issue in another environment?

**Comment by bcruga** [comment] 2017-05-08 16:44
Sorry I can't reproduce it in another environment, only python.

**Comment by jsstylos** [comment] 2017-05-08 17:18
Can you reproduce it on a different machine?

**Comment by davidsilvam** [comment] 2017-05-26 13:18
Same problem here. Someone solved?

**Comment by jsstylos** [comment] 2017-05-30 20:33
@davidsilvam I was never able to reproduce the original issue. Do you have a zip file that fails to process with the Python SDK but works with https://watson-api-explorer.mybluemix.net/apis/visual-recognition-v3#!/visual45recognition/post_v3_classify ? If so can you upload that file somewhere to test?

**Comment by chughts** [comment] 2017-05-31 06:15
I don't think that this is Python specific, as this developerworks forum conversation ( https://developer.ibm.com/answers/questions/377690/error-400-when-trying-to-create-a-custom-classifie/ ) refers to a similar problem, but this time making use of both cURL and Node.js.

I think the problem is actually OS related, in particular the way the OS handles zip folders. I don't know which OS yet. So anyone facing this problem, can you please tell us which OS your are running on.

**Comment by jsstylos** [comment] 2017-05-31 18:53
@chughts The 35.zip file above exhibits the problem for the original poster, but I can't reproduce it. If we can get a reproducible source file then we should be able to address the problem.

**Comment by chughts** [comment] 2017-06-01 09:12
@jsstylos Just seen this response to my response to the question in developerworks answers - 

> Thanks, it works now! I have tried before placing the images at the root level inside the zip, but it didn't work so I decided to follow IBM's example. Now I decided to recreate my zips inside a Linux environment.. I'm not really sure if it has anything to do with it, but it works and I'm really thankful for your help!

**Comment by jsstylos** [comment] 2017-06-01 14:08
@chughts It would be good to figure out what types of zip files don't work with the service so that we can any problems at the service level. Do you know of any zip files that can reliably reproduce the problem?

**Comment by chughts** [comment] 2017-06-01 14:38
@jsstylos You won't like this. Create a folder (say for bulbs) and name it bulbs.zip then copy image files into it.

**Comment by jsstylos** [comment] 2017-06-01 14:44
@chughts Do you have a file like that that reliably fails?

**Comment by chughts** [comment] 2017-06-01 16:49
Ones that give me a 

> curl: (43) A libcurl function was given a bad argument

 error

**Comment by neilsbhargava** [comment] 2017-06-01 20:00
Hi @jsstylos, another user checking in having the same issue. I have a zip file that I am trying to test against a trained visual recognition classifier and I am getting the following error:

`Traceback (most recent call last):
  File "daimlerVR.py", line 30, in <module>
    damaged_results = vr.classify(images_file=test_set, threshold=0.1, classifier_ids=['SimpleDamage_1258166596'])
  File "/Users/neilbhargava/Documents/colab/daimler-vr/env/lib/python2.7/site-packages/watson_developer_cloud/visual_recognition_v3.py", line 156, in classify
    params)
  File "/Users/neilbhargava/Documents/colab/daimler-vr/env/lib/python2.7/site-packages/watson_developer_cloud/visual_recognition_v3.py", line 133, in _image_call
    accept_json=True)
  File "/Users/neilbhargava/Documents/colab/daimler-vr/env/lib/python2.7/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 320, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unknown error`

I am using Mac OS X (10.11) and Python 2.7

**Comment by jsstylos** [comment] 2017-06-01 20:05
@neilsbhargava Can you upload a zip file for testing?

**Comment by neilsbhargava** [comment] 2017-06-01 20:08
@jsstylos - I can't upload the zip here due to NDA restrictions. I am an IBMer working in the Watson Org so if you are on Slack I can give you the zip privately (provided it is not shared with anyone outside of IBM).

**Comment by jsstylos** [comment] 2017-06-01 20:26
One issue here is that some zip files are returning 413 Request Entity Too Large errors (with an html content type :-/ ), even when they don't exceed the documented file size limits. This should go away in an upcoming release, but one thing to test in the meantime is what happens when attempting to classify via curl:

```
curl -X POST -F "images_file=@test.zip" "https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classify?api_key=your-api-key&version=2016-05-20" -v
```

If anyone has a file that succeeds via curl but reliably fails via the Python SDK I would very much like to see it.

If anyone has a file that fails via curl but should succeed (the files are below the stated size limits, etc.) then that would be good to see also, although do to an upcoming implementation change it is likely to get fixed in an upcoming change to the service regardless.

**Comment by davidsilvam** [comment] 2017-06-07 14:45
@jsstylos I tested the upload the same .zip in https://watson-api-explorer.mybluemix.net/apis/visual-recognition-v3#!/visual45recognition/post_v3_classify in Windows 10 and in Debian. The response in Debian was positive, while in Windows the return erro is  "description": "No images were specified.",  "error_id": "input_error"...

**Comment by chughts** [comment] 2017-06-08 08:20
Could this be related to creating zips using npm archiver - RE this response on DeveloperWorks Answers?

> OK, I will try to simplified the steps for recreation tomorrow. And don't think it is a zipping problem as when I increase the image number from 15 to 40 in the zip file. it works completely fine with the same zipping method - I am actually using NPM archiver to zip the images in the folder.

**Comment by chughts** [comment] 2017-06-19 18:52
Attaching 2 zip files that fail - 2 x Positive Images.
[fix.zip](https://github.com/watson-developer-cloud/python-sdk/files/1086010/fix.zip)
[swap.zip](https://github.com/watson-developer-cloud/python-sdk/files/1086011/swap.zip)

**Comment by 5agado** [comment] 2017-07-05 15:02
Any updates regarding the issue? I am encountering the same problem. Single zip file with single image using Python 3.4 on Windows 7.

**Comment by germanattanasio** [comment] 2017-07-06 02:38
When sending the requests are you sending `application/octet-stream` as `Content-Type`? because the service is expecting that along with the zip file.

**Comment by OndrejSzekely** [comment] 2017-07-09 11:35
I have the same problem. It is working fine on Mac OS - zip folder, and score ...On windows error from watson service - no image inside folder. Could you please fix it?

**Closed** 2017-07-28 14:47 UTC
Labels: bug

**Comment by rosine** [comment] 2017-09-27 02:59
Hello, could anyone solve the problem? 
I still get the problem even when using a zip file containing just one image. I am using windows 10.
