### ISSUE TITLE
SysCallError(10054) and SysCallError(-1) watson NLU Errors

### ISSUE THREAD

**Issue by Godase** [watson-developer-cloud/python-sdk#591] opened 2018-10-30 11:34 UTC
#### Expected behavior
- All request should work correctly without any error.

#### Actual behavior
**When I passed multiple request to the IBM Watson natural language understanding API then I got two errors**
**First one is :-**
invalid literal for int() with base 10: 'port=443): Max retries exceeded with url: /natural-language-understanding/api/v1/analyze?version=2018-03-16 (Caused by SSLError(SSLError(\"bad handshake: SysCallError(10054'"

**Second one is :-**
invalid literal for int() with base 10: 'port=443): Max retries exceeded with url: /natural-language-understanding/api/v1/analyze?version=2018-03-16 (Caused by SSLError(SSLError(\"bad handshake: SysCallError(-1'"

#### Steps to reproduce the problem
- Multiple request per second 

#### Code snippet (Note: Do not paste your credentials)
```
            natural_language_understanding = NaturalLanguageUnderstandingV1(
                url=self.set_object.watson_nlu_url,
                version='2018-03-16',
                username=self.set_object.watson_nlu_username,
                password=self.set_object.watson_nlu_password)

            # Calling the Watson Natural language understanding API
            natural_language_understanding.disable_SSL_verification()
            try:
                response = natural_language_understanding.analyze(
                    text=str(user_answer_sent),
                    features=Features(
                        semantic_roles=SemanticRolesOptions(),
                        sentiment=SentimentOptions()
                    ), language='en'
                ).get_result()
```
#### python version
3.6.6

#### watson-developer-cloud python sdk version
2.4.0

**Is there any limit for multiple calls per seconds in NLU lite plan?**

**Comment by ehdsouza** [comment] 2018-10-30 14:06
@Godase to help you better, could you update the issue description with the issue template:
#### Expected behavior

#### Actual behavior

#### Steps to reproduce the problem

#### Code snippet (Note: Do not paste your credentials)

#### python sdk version

#### python version

**Comment by Godase** [comment] 2018-10-31 06:54
> @Godase to help you better, could you update the issue description with the issue template:
> 
> #### Expected behavior
> #### Actual behavior
> #### Steps to reproduce the problem
> #### Code snippet (Note: Do not paste your credentials)
> #### python sdk version
> #### python version

@ehdsouza Please check the updated issue with description

**Comment by ehdsouza** [comment] 2018-10-31 17:49
@Godase, if you are doing concurrent requests, then yes there is a limit.

However, `Max retries exceeded with url: /natural-language-understanding/api/v1/analyze?version=2018-03-16 (Caused by SSLError(SSLError("bad handshake: SysCallError(10054'"` was seen by another user earlier who had to create a new instance to avoid the SSL error (as this would be a service error and not a problem with the SDK).

To investigate more from the service side, you could create a ticket: https://console.bluemix.net/unifiedsupport/tickets/add

**Comment by Godase** [comment] 2018-11-01 05:28
> @Godase, if you are doing concurrent requests, then yes there is a limit.
> 
> However, `Max retries exceeded with url: /natural-language-understanding/api/v1/analyze?version=2018-03-16 (Caused by SSLError(SSLError("bad handshake: SysCallError(10054'"` was seen by another user earlier who had to create a new instance to avoid the SSL error (as this would be a service error and not a problem with the SDK).
> 
> To investigate more from the service side, you could create a ticket: https://console.bluemix.net/unifiedsupport/tickets/add

@ehdsouza If we moved to premium plan is there any changes to increase the concurrent request limit?

**Comment by ehdsouza** [comment] 2018-11-01 20:44
Look into the usage limits here: https://console.bluemix.net/docs/services/natural-language-understanding/usage-limits.html#analyzed-text

**Comment by ehdsouza** [comment] 2018-11-05 22:41
This link talks about the concurrent requests limit: https://console.bluemix.net/docs/services/natural-language-understanding/usage-limits.html#analyzed-text

You could open a support ticket to get more information from the service team.

**Comment by ehdsouza** [comment] 2018-11-30 18:40
@Godase would you need any more help with the SDK? Let me know if I can close this.

**Comment by Godase** [comment] 2018-12-12 06:34
@ehdsouza you can close this.

**Closed** 2018-12-12 14:39 UTC
Labels: support
