### ISSUE TITLE
Discovery returns empty JSON

### ISSUE THREAD

**Issue by GuiJordao21** [watson-developer-cloud/python-sdk#337] opened 2017-12-22 10:32 UTC
I'm trying to use discovery, but it returns an empty JSON, just that, there is no error message and any other kind of feedback.

The weirdest part is that on my friends mac, it works ok.

Any ideas?

**Comment by ammardodin** [comment] 2017-12-22 21:12
@GuiJordao21 Thanks for reporting the issue. Can you please provide the following info:
1. Version of the SDK you're using
2. The Discovery method you're calling
3. A code snippet so that we can try to reproduce the issue

Thanks,

**Comment by GuiJordao21** [comment] 2017-12-23 22:07
I'm going to sent this tuesday, because I left everything at work.
But I left the sdk and used the query to get the return I was expecing. It works ok when it's running local, but it gives me an internal server error when i upload to blueMix.

Thx so much for the reply! I'll provide more info soon.

**Comment by germanattanasio** [comment] 2017-12-26 18:47
Hey, @GuiJordao21 any change you can answer @ammardodin's questions above?

**Comment by GuiJordao21** [comment] 2017-12-27 10:08
So sorry about the delay, I had a really busy day yesterday.

SDK's version is 1.0.2
I'm using DiscoveryV1().query

and here is a code snippet

#StartCode
import os
import sys
import json
from watson_developer_cloud import DiscoveryV1

def main(frase):

    discovery = DiscoveryV1(
            username="username",
            password="password",
            version="2017-11-07"
        )

    print(frase)
    qopts = {'query': frase}
    my_query = discovery.query('id','id',qopts)
    textos = json.dumps(my_query)
    textos = json.loads(textos)

    lista = {}
    num = 1

    print(len(textos['results']))
    # print(textos['results'][0]['text'])

    for i in range(0,len(textos['results'])):
        lista.update({str(num):textos['results'][i]['text']})
        num = int(num)+1
        print(textos['results'][i]['text'])
        print(i)

    # return textos['results'][0]['text']
    return lista
if __name__=="__main__":
    main()

One of the strangest things is that this same codes works on my boss mac, but not on my windows, so maybe is an OS problem? don't really know.

Again, I'm very sorry, had a busy day yesterday.
Thx so much for your atention.

**Comment by ammardodin** [comment] 2017-12-27 20:20
@GuiJordao21 is the `textos` object always empty? Or is it just the `results` field? If it's the later, it's likely because your query didn't match anything.

**Comment by GuiJordao21** [comment] 2017-12-28 10:50
@ammardodin it's always empty. I'm sure the query has results, because when I use Discovery's build query, on IBM Cloud, works, I get results also when using a url for the search. It's very odd, I really have no ideai of what's happening!

**Comment by ehdsouza** [comment] 2018-01-02 17:16
@GuiJordao21 could you show how the query looks?

**Comment by GuiJordao21** [comment] 2018-01-03 10:22
`r = requests.get('https://gateway.watsonplatform.net/discovery/api/v1/environments/<env_ID>/collections/<coll_ID>/query?version=2017-11-07&deduplicate=false&highlight=true&passages=true&passages.count=5&query'=+frase)`

This way, I'am able to get the results from discovery. But it's always empty when I try to use 

`my_query = discovery.query('id','id',qopts)`

with the same String in it, I get an empty JSON.

**Comment by ehdsouza** [comment] 2018-01-03 16:35
It could be that you are inputing the `qopts` incorrectly. Could you show how yours looks like? 

Also you mentioned that the query works on mac. By this do you mean the python way ie `my_query = discovery.query('id','id',qopts)` works on mac and not windows?

**Comment by GuiJordao21** [comment] 2018-01-03 19:07
`qopts = {'query' : '<query string>'}`

when we insert a <query string> like "I like to eat bananas" or whatever,
          on mac = I got results
          on windows = nothing

**Comment by ehdsouza** [comment] 2018-01-03 21:18
Hi,

1) Could you try to run the discovery example: https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/discovery_v1.py
2) Which version of python is running on mac and windows
3) You could also enable debugging by uncommenting the debug code in https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/watson_service.py to check the request

**Comment by GuiJordao21** [comment] 2018-01-04 10:30
ok! I'll do this as soon as possible! thx for the help!

**Comment by ehdsouza** [comment] 2018-01-04 15:03
Thanks. Also, having special characters in the query could be an issue. Look at https://github.com/watson-developer-cloud/python-sdk/issues/185

**Comment by hoffj66** [comment] 2018-01-05 14:28
A colleague and I just experienced this.  His same file was working on my Windows system and failing on his Mac.  I was able to get it to fail after I updated my python sdk to the newest version.  I don't know which version I had, but it was working.
Old version - lots of results
New version - zero results
exact same python code

**Comment by hoffj66** [comment] 2018-01-06 00:24
It looks like the interface changed.   It was previously:
def query(self, environment_id, collection_id, query_options):
and now it is:
def query(self,
              environment_id,
              collection_id,
              filter=None,
              query=None,
              natural_language_query=None,
              passages=None,
              aggregation=None,
              count=None,
              return_fields=None,
              offset=None,
              sort=None,
              highlight=None,
              passages_fields=None,
              passages_count=None,
              passages_characters=None,
              deduplicate=None,
              deduplicate_field=None):

Thus the third parameter is all being put into 'filter' now.

**Comment by germanattanasio** [comment] 2018-01-15 16:08
@hoffj66 we did a major release with some breaking changes. Make sure you read the [Migration guide](https://github.com/watson-developer-cloud/python-sdk/wiki/Migration) it could be that you are using the old code with the new interface.

**Comment by hoffj66** [comment] 2018-01-15 17:53
@germanattanasio .  That makes sense.  The problem seems to be that the WDS API documentation (https://www.ibm.com/watson/developercloud/discovery/api/v1/#query-collection) hasn't been updated.  This is the code that is currently online and it shows the old interface method.  For anyone trying to get this going, it will be confusing.  They won't get any errors but the result will almost always be wrong.

discovery = DiscoveryV1(
  username="{username}",
  password="{password}",
  version="2017-11-07"
)

qopts = {'query': '{query_string}', 'filter': '{filter_string}', ...}
my_query = discovery.query('{environment_id}', '{collection_id}', qopts)
print(json.dumps(my_query, indent=2))

**Comment by germanattanasio** [comment] 2018-01-15 22:01
100% agree with you @hoffj66. I'm going to tell the team to update that page

**Comment by NickyBleiel** [comment] 2018-01-19 18:43
Thanks for pointing this out. We have an issue for it  in the queue and plan to update the Python SDK next week.

**Comment by germanattanasio** [comment] 2018-02-02 22:14
I'm closing this since it's not a problem with the SDK. From what I know the API Reference will be updated in 2 weeks. Feel free to reopen if you think the issue is in the SDK but provide a way to reproduce it with > v1.0

**Closed by germanattanasio** 2018-02-02 22:14 UTC
Labels: support
