### ISSUE TITLE
Attempt to fetch failed: :closed

### ISSUE THREAD

**Issue by jasonfox** [watson-developer-cloud/python-sdk#199] opened 2017-05-02 15:38 UTC
We are receiving this vague error for certain URLs when using Watson's NLU API. I saw in [a previously closed issue](https://github.com/watson-developer-cloud/python-sdk/issues/182) that the cause might be the site's robots.txt preventing Watson from scraping the URL. 

However, in our case, it doesn't seem to be the issue. Also, in cases when robots.txt was blocking Watson we've seen this, appropriate error message: "Request to fetch blocked: disallowed."  

Here is an example URL that yields this error: https://www.unionathletics.com/news/2017/5/1/womens-outdoor-track-field-bechu-collects-third-straight-liberty-league-performer-of-the-week-honors.aspx

And their robots.txt which doesn't seem like it should block Watson: https://www.unionathletics.com/robots.txt

Could someone explain what this error means: **Attempt to fetch failed: :closed**? Any help would be appreciated.

Thanks in advance,
Jason

_PS - I have noticed that this site wants a User-Agent set in the request. I checked and see that Watson does set the User-Agent string when fetching URLs to: "watson-url-fetcher", so, I don't think that's the issue, but maybe?_

**Comment by jsstylos** [comment] 2017-05-03 19:07
One potential issue in the `robots.txt` is:

```
User-agent: *
... 
Visit-time: 0100-0645
```

Which looks like it should disallow requests that aren't between 1am and 6:45am GMT. I can't tell if there are other issues, or why the response is different, but I have an issue opened internally on improving the error message for rejected requests.

**Comment by jasonfox** [comment] 2017-05-04 19:21
Thanks for your reply. I missed that in the robots.txt and I bet that does explain it. Normally, the process we have that uses the NLU API runs over night, so, in production it probably should be fine; this issue came up in testing during the day. 

Also, thanks for putting in the request to improve the error message. I'll close this issue now.

**Comment by jasonfox** [comment] 2017-07-06 15:01
I came across a new site for which Watson gives me the same error `Attempt to fetch failed: :closed`  However, the site appears to be valid, i.e., if you pass the HTML through the W3C validator it comes out [mostly fine](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.knox.edu%2Fnews%2Fknox-college-elects-new-trustees) and robots.txt doesn't appear to preclude crawlers like the previous example did.  Could anyone shed some light on this?

Here's the URL: https://www.knox.edu/news/knox-college-elects-new-trustees

**Comment by germanattanasio** [comment] 2017-07-28 15:20
@jasonfox I think this is not an issue in the SDK. The service seems to be failing to fetch the URL.

**Comment by jasonfox** [comment] 2017-07-28 17:22
Yes, I agree. As a work-around, we're currently fetching the URLs ourselves and then passing the HTML to Watson. However, since you work at IBM on the Watson team, could you or someone else provide some insight as to why Watson is unable to fetch this URL?

**Comment by germanattanasio** [comment] 2017-07-28 17:28
Yes, I can do that

**Comment by germanattanasio** [comment] 2017-07-28 17:28
@g-may do you know someone on the NLU team?

**Comment by shribe** [comment] 2017-08-07 19:22
`Attempt to fetch failed: :closed` means the connection to the server dropped before the response was received.

**Comment by germanattanasio** [comment] 2017-08-08 17:48
@shribe I'm going to leave this open until we fix it in the service

**Comment by px350** [comment] 2017-10-04 14:44
I'm experiencing the exact same problem as jasonfox (Attempt to fetch failed: :closed). Everything's fine with robots.txt. No user-agent or page/directory are blocked and, just to be sure, I even added permissions to the one supposedly used by Watson (watson-url-fetcher). When you speak of "fixing the service", what are you actually referring to?

**Comment by px350** [comment] 2017-10-08 17:01
To be ignored is quite unpleasant. Unless this supposed "fix it in the service" was too challenging!?!

**Comment by germanattanasio** [comment] 2017-10-08 17:22
@px350 This is not an issue for this repository but a problem with the service. I opened a ticket with Bluemix support but I don't know when it will get fixed. I'll post an update here once they close my support ticket. 

You should also open a [ticket](https://support.ng.bluemix.net/supportticket/?app=technicalsupport&index=13) maybe that helps

**Comment by ehdsouza** [comment] 2017-11-15 16:18
Closing the issue as the problem is not with the sdk and issues to services can be opened at [ticket](https://watson.service-now.com/wcp)

**Closed by ehdsouza** 2017-11-15 16:18 UTC
Labels: support
