### ISSUE TITLE
AssertionError when Pip installing sdk in DSX

### ISSUE THREAD

**Issue by tylernd27** [watson-developer-cloud/python-sdk#405] opened 2018-03-13 19:05 UTC
#### Expected behavior
Install with no issue.
#### Actual behavior
AssertionError
#### Steps to reproduce the problem
`!pip install --upgrade watson-developer-cloud` in DSX
#### Code snippet (Note: Do not paste your credentials)
```
AssertionError: Multiple .dist-info directories: /gpfs/fs01/user/sd8e-783f77b5534e01-6650b5108aaf/.local/lib/python3.5/site-packages/zope.interface-4.4.3.dist-info, /gpfs/fs01/user/sd8e-783f77b5534e01-6650b5108aaf/.local/lib/python3.5/site-packages/zope.interface-4.4.2.dist-info
```
#### python sdk version
all, but specifically happened first when running `!pip install --upgrade watson-developer-cloud==1.0.1`
#### python version
3.5

**Comment by ehdsouza** [comment] 2018-03-13 19:16
This issue was reproducible in DSX. Restarting the kernel resolved it.

**Comment by tylernd27** [comment] 2018-03-13 20:30
after restarting kernel did not work --- ran `!pip install --upgrade pip`, restarted kernel and it resolved it.

**Comment by ammardodin** [comment] 2018-03-23 02:57
@tylernd27 I don't believe this is an issue with the wdc package. Looking at the errors above, I believe the problem here is that it appears that `DSX` specifies a custom build directory for `pip`. `pip` doesn't actively manage custom build directories, since those are usually used for incremental build optimizations. As such, that responsibility becomes the burden of the user, which in this case is `DSX`. I assume running `!pip install --upgrade pip` and restarting the kernel has triggered the deletion of those custom build directories, which is probably why you didn't see the error above anymore.

I've attempted to reproduce the issue in the latest release of `DSX` now `Watson Studio`, and I was unsuccessful 😞 , so maybe it has been addressed 🤞 . Can you perhaps try reproducing the issue in a new notebook now and see if the issue still persists ?

**Comment by tylernd27** [comment] 2018-03-23 14:43
I can reproduce the error when I rollback the sdk version in `DSX`. So if I upgrade to latest, restart kernel, then run `!pip install --upgrade watson-developer-cloud==1.0.1` or any previous version.

**Comment by ammardodin** [comment] 2018-03-23 15:17
Interesting... So I just tried the following:

1. Create a notebook in DSX
2. Run `!pip install --upgrade watson-developer-cloud`
3. Restart the kernel
4. Do `!pip install --upgrade watson-developer-cloud==1.0.0`

I wasn't able to reproduce the error above... @ehdsouza Can you try when you get a chance ?

**Comment by tylernd27** [comment] 2018-03-23 15:20
Can you try `1.0.1`? my assumption that all previous versions would not work may be wrong. I just tried with `1.0.0` and it worked, but `1.0.1` did not

**Comment by ammardodin** [comment] 2018-03-23 15:29
Interesting, I tried the following:

1. Create a notebook in DSX
2. Run `!pip install --upgrade watson-developer-cloud`
3. Restart the kernel
4. Do `!pip install --upgrade watson-developer-cloud==1.0.1`

I didn't see the error above with rolling back on `1.0.1` from the latest 🤔

**Comment by germanattanasio** [comment] 2018-03-23 20:51
![wtf](https://user-images.githubusercontent.com/313157/37852778-272b0b3e-2ea1-11e8-9ed8-4a6db03e6d3b.gif)

**Comment by ehdsouza** [comment] 2018-03-28 14:47
I tried to reproduce the issue in DSX but couldn't. Seems like the issue is fixed on DSX side. Anyone facing the issue, could try:
1) !pip install --upgrade pip
2) Restarting the kernel

**Closed by ehdsouza** 2018-03-28 14:47 UTC
Labels: support
